### ISSUE TITLE
Is there a way to make .tube() more tree-like?

### ISSUE THREAD

**Issue by David-Peede** [grahamgower/demesdraw#49]
Hello! 

I have recently begun using `demesdraw` and have really enjoyed it! I was wondering if there is a way to make the output of `.tube()` to appear more tree-like. For example here are the two `demes` graphs for a three-taxon tree which is a subset of the larger four-taxon tree.

Three-taxon tree:
```yaml
description: IUA
time_units: generations
demes:
- name: P123
  epochs:
  - {end_time: 2400000.0, start_size: 1000000.0}
- name: P12
  ancestors: [P123]
  epochs:
  - {end_time: 1200000.0, start_size: 1000000.0}
- name: P3
  ancestors: [P123]
  epochs:
  - {end_time: 0.0, start_size: 1000000.0}
- name: P2
  ancestors: [P12]
  epochs:
  - {end_time: 0.0, start_size: 1000000.0}
- name: P1
  ancestors: [P12]
  epochs:
  - {end_time: 0.0, start_size: 1000000.0}
pulses:
- {source: P3, dest: P2, time: 200000.0, proportion: 0.1}
```

Four-taxon tree:
```yaml
description: Introgression from P3 to P2 with an introgression proportion of 0.1 at
  time 200000.0
time_units: generations
demes:
- name: P1234
  epochs:
  - {end_time: 16000000.0, start_size: 1000000.0}
- name: P123
  ancestors: [P1234]
  epochs:
  - {end_time: 2400000.0, start_size: 1000000.0}
- name: P4
  ancestors: [P1234]
  epochs:
  - {end_time: 0.0, start_size: 1000000.0}
- name: P12
  ancestors: [P123]
  epochs:
  - {end_time: 1200000.0, start_size: 1000000.0}
- name: P3
  ancestors: [P123]
  epochs:
  - {end_time: 0.0, start_size: 1000000.0}
- name: P2
  ancestors: [P12]
  epochs:
  - {end_time: 0.0, start_size: 1000000.0}
- name: P1
  ancestors: [P12]
  epochs:
  - {end_time: 0.0, start_size: 1000000.0}
pulses:
- {source: P3, dest: P2, time: 200000.0, proportion: 0.1}
```

I then plot both graphs with the following code:

```python
# Load graphs.
three_taxon = demes.load('./data/demes_yamls/three_taxon_tree_graph_f_01.yaml')
four_taxon = demes.load('./data/demes_yamls/four_taxon_tree_graph_f_01.yaml')
# Visualize the graphs.
fig, ax = plt.subplots(figsize=(12,9))
demesdraw.tubes(three_taxon, ax=ax, title='Three-Taxon Tree', seed=42)
plt.show()
fig, ax = plt.subplots(figsize=(12,9))
demesdraw.tubes(four_taxon, ax=ax, title='Four-Taxon Tree', seed=42)
plt.show()
```

Which outputs:
![three_taxon_tree_f_01](https://user-images.githubusercontent.com/56041628/142421095-aba55e06-3435-4e69-a74b-137aa0606d28.png)
![four_taxon_tree_f_01](https://user-images.githubusercontent.com/56041628/142421107-bab494d2-610a-4dee-9e85-82df4c6bb51a.png)

I find the three-taxon tree visualization very appealing and would like to view the four-taxon tree in that "tree-like" manner as well. I know the documentation says that `demesdraw` focus at the moment is to create example for the `demes` documentation, but was wondering if there is functionality to make the `.tube()` more tree-like?

Thanks!
-Dave
